version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pw2_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pw2db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pw2-network

  backend:
    container_name: pw2_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - pw2-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pw2db

  frontend:
    container_name: pw2_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
    depends_on:
      - backend
    networks:
      - pw2-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  pw2-network:
    driver: bridge
